name: C++ build with CMake

# Controls when the action will run:
# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ubuntu-gcc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: configure
      run: mkdir build && cd build && CXX=g++ cmake -DIqsMPI=OFF -DIqsUtest=ON ..
    - name: build
      run: cmake --build build

    - name: unit test
      run: ./build/bin/utest
