name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, development ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t intel-qs:$(date +%s) .
